version: "3.8"
services:
  selenium:
    image: selenium/standalone-chrome:3.141
    hostname: localhost
    ports:
      - 4444:4444

  blog_exporter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    command: ["/bin/bash", "./wait-for-it-master/wait-for-it.sh", "localhost:4444", "--", "python", "./src/main.py"]
    volumes:
      - "./output:/app/output"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    command: [ "/bin/bash", "./wait-for-it-master/wait-for-it.sh", "localhost:4444", "--", "python", "-m", "unittest", "tests.website_test" ]
